---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://dev-api.stackbit.com/project/5c4f55292662a0000f0111f8/webhook/forestry
sections:
- type: document
  path: _config.yml
  label: Config
  templates:
  - config
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
- type: document
  path: elements.md
  label: Elements
  templates:
  - elements
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
